import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { PYIDAUNGSU_FONT_BASE64 } from "./fonts/mm-font";

const containsMyanmar = (text: string = "") => /[\u1000-\u109F]/.test(text);

export const generateAttendanceReportPDF = (
  batchInfo: { course_name: string; batch_no: string; start_date?: string | null; end_date?: string | null; is_active: boolean },
  monthFilter: string | null,
  totalClasses: number,
  students: any[],
  generatedBy: string = "Admin"
) => {
  const doc = new jsPDF("p", "mm", "a4");

  const hasMyanmarFont = PYIDAUNGSU_FONT_BASE64 && PYIDAUNGSU_FONT_BASE64.length > 10000;
  if (hasMyanmarFont) {
    try {
      doc.addFileToVFS("Pyidaungsu.ttf", PYIDAUNGSU_FONT_BASE64);
      doc.addFont("Pyidaungsu.ttf", "Pyidaungsu", "normal");
    } catch (e) {
      console.error("Failed to register Myanmar font:", e);
    }
  }

  const setCorrectFont = (text: string | undefined, size: number = 10, style: string = "normal") => {
    const str = text || "";
    doc.setFontSize(size);
    if (hasMyanmarFont && containsMyanmar(str)) {
      doc.setFont("Pyidaungsu", style);
    } else {
      doc.setFont("helvetica", style);
    }
  };

  const getMonthName = (monthStr: string | null) => {
    if (!monthStr) return "All Time";
    const [year, month] = monthStr.split("-");
    const date = new Date(Number(year), Number(month) - 1, 1);
    return date.toLocaleString("default", { month: "long", year: "numeric" });
  };

  // Header Title
  setCorrectFont("NiT College - Student Management System", 9, "bold");
  doc.setTextColor(100, 116, 139); // Slate color
  doc.text("NiT College - Student Management System", 14, 15);
  
  setCorrectFont("BATCH ATTENDANCE REPORT", 16, "bold");
  doc.setTextColor(79, 70, 229); // Indigo-600 color
  doc.text("BATCH ATTENDANCE REPORT", 14, 23);
  doc.setTextColor(0, 0, 0); // Reset

  // Info Section
  setCorrectFont("Report Details", 10, "bold");
  doc.text("Report Details", 14, 32);

  setCorrectFont(`Course Name: ${batchInfo.course_name}`, 9, "normal");
  doc.text(`Course Name: ${batchInfo.course_name}`, 14, 37);
  doc.text(`Batch Number: ${batchInfo.batch_no}`, 14, 42);
  doc.text(`Status: ${batchInfo.is_active ? "Active" : "Ended"}`, 14, 47);

  // Right column of info
  const rightColumnX = 120;
  doc.text(`Report Period: ${getMonthName(monthFilter)}`, rightColumnX, 37);
  doc.text(`Total Classes: ${totalClasses} sessions`, rightColumnX, 42);
  doc.text(`Generated By: ${generatedBy}`, rightColumnX, 47);
  doc.text(`Generated At: ${new Date().toLocaleString()}`, rightColumnX, 52);

  const pageWidth = doc.internal.pageSize.getWidth();

  // Divider Line
  doc.setLineWidth(0.5);
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.line(14, 56, pageWidth - 14, 56);

  // Headers and Rows mapping
  const headers = [
    "Student Name",
    "Code",
    monthFilter ? `Attendance (${getMonthName(monthFilter).split(" ")[0]})` : "Attendance (Recent Month)",
    monthFilter ? `Rate (${getMonthName(monthFilter).split(" ")[0]})` : "Rate (Recent Month)",
    "Overall Attendance",
    "Overall Rate"
  ];

  const rows = students.map(s => {
    const monthlySpec = s.monthly_specific;
    const monthlyText = monthlySpec 
      ? `${monthlySpec.present} / ${monthlySpec.total}`
      : `${s.month.present} / ${s.month.total}`;
    
    const monthlyRateText = monthlySpec
      ? (monthlySpec.percentage === null ? "—" : `${monthlySpec.percentage}%`)
      : (s.month.percentage === null ? "—" : `${s.month.percentage}%`);

    return [
      s.username || "Unknown",
      s.user_code || "",
      monthlyText,
      monthlyRateText,
      `${s.overall.present} / ${s.overall.total}`,
      s.overall.percentage === null ? "—" : `${s.overall.percentage}%`
    ];
  });

  // Table rendering
  autoTable(doc, {
    startY: 61,
    head: [headers],
    body: rows,
    theme: "striped",
    headStyles: { fillColor: [79, 70, 229] }, // Indigo-600 header
    styles: { fontSize: 8.5, cellPadding: 3 },
    columnStyles: {
      1: { halign: "center" },
      2: { halign: "center" },
      3: { halign: "center" },
      4: { halign: "center" },
      5: { halign: "center" }
    },
    didDrawCell: (data) => {
      // Add font logic if Pyidaungsu is used for Myanmar characters
      if (hasMyanmarFont && data.section === 'body') {
        const text = data.cell.text.join('\n');
        if (containsMyanmar(text)) {
          data.cell.styles.font = "Pyidaungsu";
        }
      }
    }
  });

  // Save the PDF
  const filename = `AttendanceReport_${batchInfo.course_name.replace(/\s+/g, '_')}_${batchInfo.batch_no.replace(/\s+/g, '_')}_${monthFilter || "overall"}.pdf`;
  doc.save(filename);
};
