import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { PYIDAUNGSU_FONT_BASE64 } from "./fonts/mm-font";
import { getExtraItemNames, getExtraItemPrices, getExtraItemMethods, formatSpecificDate } from "./format";

const containsMyanmar = (text: string = "") => /[\u1000-\u109F]/.test(text);

export const generateIncomeReportPDF = (
  type: "daily" | "weekly" | "monthly",
  data: any[],
  dateRange: string = "All Time",
  generatedBy: string = "Admin",
  paymentRecords: any[] = []
) => {
  const doc = new jsPDF("l", "mm", "a4");

  
  const hasMyanmarFont = PYIDAUNGSU_FONT_BASE64 && PYIDAUNGSU_FONT_BASE64.length > 10000;
  if (hasMyanmarFont) {
    try {
      doc.addFileToVFS("Pyidaungsu.ttf", PYIDAUNGSU_FONT_BASE64);
      doc.addFont("Pyidaungsu.ttf", "Pyidaungsu", "normal");
    } catch (e) {
      console.error("Failed to register Myanmar font:", e);
    }
  }

  const setCorrectFont = (text: string | undefined, size: number = 10, style: string = "normal") => {
    const str = text || "";
    doc.setFontSize(size);
    if (hasMyanmarFont && containsMyanmar(str)) {
      doc.setFont("Pyidaungsu", style);
    } else {
      doc.setFont("helvetica", style);
    }
  };

  // Header Title
  setCorrectFont("NiT College - Student Management System", 10, "bold");
  doc.text("NiT College - Student Management System", 14, 15);
  
  setCorrectFont("FINANCIAL INCOME REPORT", 16, "bold");
  doc.setTextColor(63, 81, 181); // Indigo color
  doc.text("FINANCIAL INCOME REPORT", 14, 23);
  doc.setTextColor(0, 0, 0); // Reset

  // Info Section
  setCorrectFont(`Report Type: ${type.toUpperCase()}`, 9, "normal");
  doc.text(`Report Type: ${type.toUpperCase()}`, 14, 32);
  doc.text(`Date Range: ${dateRange}`, 14, 37);
  doc.text(`Generated By: ${generatedBy}`, 14, 42);
  doc.text(`Generated At: ${new Date().toLocaleString()}`, 14, 47);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Divider Line
  doc.setLineWidth(0.5);
  doc.setDrawColor(220, 220, 220);
  doc.line(14, 52, pageWidth - 14, 52);

  // Headers and Rows mapping
  const headers = [
    type === "daily" ? "Date" : type === "weekly" ? "Week Starting" : "Month",
    "Payments",
    "Tuition (MMK)",
    "Exam (MMK)",
    "Extra Items (MMK)",
    "Fines (MMK)",
    "Total (MMK)",
    "Total (GBP)"
  ];

  const rows = data.map(item => [
    type === "weekly" 
      ? formatSpecificDate(item.week_starting || item.label) 
      : (item.label || item.day || item.month),
    item.payment_count || 0,
    (item.tuition_mmk || 0).toLocaleString(),
    (item.exam_mmk || 0).toLocaleString(),
    (item.extra_mmk || 0).toLocaleString(),
    (item.fine_mmk || 0).toLocaleString(),
    (item.total_mmk || 0).toLocaleString(),
    (item.total_gbp || 0).toLocaleString()
  ]);

  // Table rendering
  autoTable(doc, {
    startY: 57,
    head: [headers],
    body: rows,
    theme: "striped",
    headStyles: { fillColor: [63, 81, 181] }, // Indigo header
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    columnStyles: {
      1: { halign: "center" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
      6: { halign: "right" },
      7: { halign: "right" }
    }
  });

  const finalY = (doc as any).lastAutoTable.finalY || 70;

  // Summary Calculations
  const totalMMK = data.reduce((sum, item) => sum + (item.total_mmk || 0), 0);
  const totalGBP = data.reduce((sum, item) => sum + (item.total_gbp || 0), 0);
  const totalCount = data.reduce((sum, item) => sum + (item.payment_count || 0), 0);

  // Summary Box at bottom
  if (finalY + 45 < pageHeight - 15) {
    const summaryY = finalY + 10;
    doc.setFillColor(245, 247, 250);
    
    // Method breakdown calculations
    const methodTotals: Record<string, number> = {};
    const addAmount = (method: string | null | undefined, amount: number) => {
      if (!amount || amount <= 0) return;
      const m = (method || "Unknown").trim();
      methodTotals[m] = (methodTotals[m] || 0) + amount;
    };
    for (const p of paymentRecords) {
      addAmount(p.payment_method, p.amount || 0);
      addAmount(p.payment_method_2, p.amount_2 || 0);
      addAmount(p.payment_method, p.fine_amount || 0);
      addAmount(p.exam_fee_payment_method || p.payment_method, p.exam_fee_paid_mmk || 0);
      const itemsStr = p.extra_items || "";
      let itemsParsed = false;
      if (itemsStr.startsWith("[") && itemsStr.endsWith("]")) {
        try {
          const parsed = JSON.parse(itemsStr);
          if (Array.isArray(parsed)) {
            itemsParsed = true;
            for (const it of parsed) {
              addAmount(it.method || p.extra_items_payment_method || p.payment_method, Number(it.price) || 0);
            }
          }
        } catch {}
      }
      if (!itemsParsed && p.extra_items_fee > 0) {
        addAmount(p.extra_items_payment_method || p.payment_method, p.extra_items_fee || 0);
      }
    }
    
    const entries = Object.entries(methodTotals);
    const methodLines: string[] = [];
    for (let i = 0; i < entries.length; i += 4) {
      const chunk = entries.slice(i, i + 4);
      methodLines.push(chunk.map(([m, val]) => `${m}: ${val.toLocaleString()} MMK`).join("      |      "));
    }
    
    const summaryHeight = 22 + (methodLines.length > 0 ? 8 + methodLines.length * 5 : 0);
    doc.roundedRect(14, summaryY, pageWidth - 28, summaryHeight, 3, 3, "F");
    
    setCorrectFont("SUMMARY STATS", 9, "bold");
    doc.text("SUMMARY STATS", 18, summaryY + 7);
    
    setCorrectFont(`Total Transactions: ${totalCount}`, 8.5, "normal");
    doc.text(`Total Transactions: ${totalCount}`, 18, summaryY + 13);
    doc.text(`Total MMK Income: ${totalMMK.toLocaleString()} MMK`, 18, summaryY + 19);
    doc.text(`Total GBP Income: ${totalGBP.toLocaleString()} GBP`, 150, summaryY + 19);
    
    if (methodLines.length > 0) {
      setCorrectFont("Income by Payment Method:", 8, "bold");
      doc.text("Income by Payment Method:", 18, summaryY + 25);
      
      setCorrectFont("", 8, "normal");
      methodLines.forEach((line, idx) => {
        doc.text(line, 18, summaryY + 30 + idx * 5);
      });
    }
  }


  if (paymentRecords && paymentRecords.length > 0) {
    // Add page break before detailed transactions (Landscape A4)
    doc.addPage("a4", "l");
    
    // Header for details
    setCorrectFont("DETAILED STUDENT TRANSACTIONS", 11, "bold");
    doc.setTextColor(63, 81, 181);
    doc.text("DETAILED STUDENT TRANSACTIONS", 14, 15);
    doc.setTextColor(0, 0, 0);
    
    const detailHeaders = [
      "Date",
      "Receipt ID",
      "Student",
      "Course",
      "Tuition (MMK)",
      "Tuition Method",
      "Exam Fee",
      "Extra Item Name",
      "Extra Item Price (MMK)",
      "Extra Payment Method",
      "Fines (MMK)",
      "Total (MMK)",
      "Total (GBP)"
    ];
    
    const detailRows: any[] = [];
    for (const p of paymentRecords) {
      if (p.amount_2 && p.amount_2 > 0) {
        // Row 1: Primary Payment
        detailRows.push([
          p.payment_date ? new Date(p.payment_date).toLocaleDateString() : "-",
          p.receipt_id || "N/A",
          `${p.student_name || "N/A"}`,
          p.course_name || "N/A",
          (p.amount || 0).toLocaleString(),
          p.payment_method || "-",
          p.exam_fee_paid_gbp > 0 
            ? `${p.exam_fee_paid_gbp} GBP` 
            : p.exam_fee_paid_mmk > 0 
              ? `${p.exam_fee_paid_mmk.toLocaleString()} MMK` 
              : "-",
          getExtraItemNames(p.extra_items),
          getExtraItemPrices(p.extra_items, p.extra_items_fee),
          getExtraItemMethods(p.extra_items, p.extra_items_payment_method),
          (p.fine_amount || 0).toLocaleString(),
          ((p.amount || 0) + (p.extra_items_fee || 0) + (p.fine_amount || 0) + (p.exam_fee_paid_mmk || 0)).toLocaleString(),
          p.exam_fee_paid_gbp > 0 ? `${p.exam_fee_paid_gbp.toLocaleString()} GBP` : "-"
        ]);
        // Row 2: Secondary Split Payment
        detailRows.push([
          p.payment_date ? new Date(p.payment_date).toLocaleDateString() : "-",
          `${p.receipt_id || "N/A"} (Split)`,
          `${p.student_name || "N/A"}`,
          p.course_name || "N/A",
          (p.amount_2 || 0).toLocaleString(),
          p.payment_method_2 || "-",
          "-",
          "-",
          "-",
          "-",
          "-",
          (p.amount_2 || 0).toLocaleString(),
          "-"
        ]);
      } else {
        // Single payment row
        detailRows.push([
          p.payment_date ? new Date(p.payment_date).toLocaleDateString() : "-",
          p.receipt_id || "N/A",
          `${p.student_name || "N/A"}`,
          p.course_name || "N/A",
          (p.amount || 0).toLocaleString(),
          p.payment_method || "-",
          p.exam_fee_paid_gbp > 0 
            ? `${p.exam_fee_paid_gbp} GBP` 
            : p.exam_fee_paid_mmk > 0 
              ? `${p.exam_fee_paid_mmk.toLocaleString()} MMK` 
              : "-",
          getExtraItemNames(p.extra_items),
          getExtraItemPrices(p.extra_items, p.extra_items_fee),
          getExtraItemMethods(p.extra_items, p.extra_items_payment_method),
          (p.fine_amount || 0).toLocaleString(),
          ((p.amount || 0) + (p.extra_items_fee || 0) + (p.fine_amount || 0) + (p.exam_fee_paid_mmk || 0)).toLocaleString(),
          p.exam_fee_paid_gbp > 0 ? `${p.exam_fee_paid_gbp.toLocaleString()} GBP` : "-"
        ]);
      }
    }
    
    autoTable(doc, {
      startY: 20,
      head: [detailHeaders],
      body: detailRows,
      theme: "striped",
      headStyles: { fillColor: [63, 81, 181] },
      styles: { fontSize: 6.5, cellPadding: 1.5, font: hasMyanmarFont ? "Pyidaungsu" : "helvetica" },
      columnStyles: {
        4: { halign: "right" },
        6: { halign: "right" },
        8: { halign: "right" },
        10: { halign: "right" },
        11: { halign: "right" },
        12: { halign: "right" }
      }
    });
  }

  // Save the PDF
  doc.save(`Income_Report_${type}_${new Date().toISOString().slice(0, 10)}.pdf`);
};
