import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { PYIDAUNGSU_FONT_BASE64 } from "./fonts/mm-font";
import { getExtraItemNames, getExtraItemPrices, formatSpecificDate } from "./format";

const containsMyanmar = (text: string = "") => /[\u1000-\u109F]/.test(text);

export const generateIncomeReportPDF = (
  type: "daily" | "weekly" | "monthly",
  data: any[],
  dateRange: string = "All Time",
  generatedBy: string = "Admin",
  paymentRecords: any[] = []
) => {
  const doc = new jsPDF("l", "mm", "a4");

  
  const hasMyanmarFont = PYIDAUNGSU_FONT_BASE64 && PYIDAUNGSU_FONT_BASE64.length > 10000;
  if (hasMyanmarFont) {
    try {
      doc.addFileToVFS("Pyidaungsu.ttf", PYIDAUNGSU_FONT_BASE64);
      doc.addFont("Pyidaungsu.ttf", "Pyidaungsu", "normal");
    } catch (e) {
      console.error("Failed to register Myanmar font:", e);
    }
  }

  const setCorrectFont = (text: string | undefined, size: number = 10, style: string = "normal") => {
    const str = text || "";
    doc.setFontSize(size);
    if (hasMyanmarFont && containsMyanmar(str)) {
      doc.setFont("Pyidaungsu", style);
    } else {
      doc.setFont("helvetica", style);
    }
  };

  // Header Title
  setCorrectFont("NiT College - Student Management System", 10, "bold");
  doc.text("NiT College - Student Management System", 14, 15);
  
  setCorrectFont("FINANCIAL INCOME REPORT", 16, "bold");
  doc.setTextColor(63, 81, 181); // Indigo color
  doc.text("FINANCIAL INCOME REPORT", 14, 23);
  doc.setTextColor(0, 0, 0); // Reset

  // Info Section
  setCorrectFont(`Report Type: ${type.toUpperCase()}`, 9, "normal");
  doc.text(`Report Type: ${type.toUpperCase()}`, 14, 32);
  doc.text(`Date Range: ${dateRange}`, 14, 37);
  doc.text(`Generated By: ${generatedBy}`, 14, 42);
  doc.text(`Generated At: ${new Date().toLocaleString()}`, 14, 47);

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Divider Line
  doc.setLineWidth(0.5);
  doc.setDrawColor(220, 220, 220);
  doc.line(14, 52, pageWidth - 14, 52);

  // Headers and Rows mapping
  const headers = [
    type === "daily" ? "Date" : type === "weekly" ? "Week Starting" : "Month",
    "Payments",
    "Tuition (MMK)",
    "Exam (MMK)",
    "Extra Items (MMK)",
    "Fines (MMK)",
    "Total (MMK)",
    "Total (GBP)"
  ];

  const rows = data.map(item => [
    type === "weekly" 
      ? formatSpecificDate(item.week_starting || item.label) 
      : (item.label || item.day || item.month),
    item.payment_count || 0,
    (item.tuition_mmk || 0).toLocaleString(),
    (item.exam_mmk || 0).toLocaleString(),
    (item.extra_mmk || 0).toLocaleString(),
    (item.fine_mmk || 0).toLocaleString(),
    (item.total_mmk || 0).toLocaleString(),
    (item.total_gbp || 0).toLocaleString()
  ]);

  // Table rendering
  autoTable(doc, {
    startY: 57,
    head: [headers],
    body: rows,
    theme: "striped",
    headStyles: { fillColor: [63, 81, 181] }, // Indigo header
    styles: { fontSize: 8.5, cellPadding: 2.5 },
    columnStyles: {
      1: { halign: "center" },
      2: { halign: "right" },
      3: { halign: "right" },
      4: { halign: "right" },
      5: { halign: "right" },
      6: { halign: "right" },
      7: { halign: "right" }
    }
  });

  const finalY = (doc as any).lastAutoTable.finalY || 70;

  // Summary Calculations
  const totalMMK = data.reduce((sum, item) => sum + (item.total_mmk || 0), 0);
  const totalGBP = data.reduce((sum, item) => sum + (item.total_gbp || 0), 0);
  const totalCount = data.reduce((sum, item) => sum + (item.payment_count || 0), 0);

  // Summary Box at bottom
  if (finalY + 35 < pageHeight - 15) {
    const summaryY = finalY + 10;
    doc.setFillColor(245, 247, 250);
    doc.roundedRect(14, summaryY, pageWidth - 28, 25, 3, 3, "F");
    
    setCorrectFont("SUMMARY STATS", 9, "bold");
    doc.text("SUMMARY STATS", 18, summaryY + 7);
    
    setCorrectFont(`Total Transactions: ${totalCount}`, 8.5, "normal");
    doc.text(`Total Transactions: ${totalCount}`, 18, summaryY + 13);
    doc.text(`Total MMK Income: ${totalMMK.toLocaleString()} MMK`, 18, summaryY + 19);
    doc.text(`Total GBP Income: ${totalGBP.toLocaleString()} GBP`, 150, summaryY + 19);
  }


  if (paymentRecords && paymentRecords.length > 0) {
    // Add page break before detailed transactions (Landscape A4)
    doc.addPage("a4", "l");
    
    // Header for details
    setCorrectFont("DETAILED STUDENT TRANSACTIONS", 11, "bold");
    doc.setTextColor(63, 81, 181);
    doc.text("DETAILED STUDENT TRANSACTIONS", 14, 15);
    doc.setTextColor(0, 0, 0);
    
    const detailHeaders = [
      "Date",
      "Receipt ID",
      "Student",
      "Course",
      "Tuition (MMK)",
      "Exam Fee",
      "Extra Item Name",
      "Extra Item Price (MMK)",
      "Extra Payment Method",
      "Fines (MMK)",
      "Total (MMK)",
      "Total (GBP)"
    ];
    
    const detailRows = paymentRecords.map(p => [
      p.payment_date ? new Date(p.payment_date).toLocaleDateString() : "-",
      p.receipt_id || "N/A",
      `${p.student_name || "N/A"}`,
      p.course_name || "N/A",
      ((p.amount || 0) + (p.amount_2 || 0)).toLocaleString(),
      p.exam_fee_paid_gbp > 0 
        ? `${p.exam_fee_paid_gbp} GBP` 
        : p.exam_fee_paid_mmk > 0 
          ? `${p.exam_fee_paid_mmk.toLocaleString()} MMK` 
          : "-",
      getExtraItemNames(p.extra_items),
      getExtraItemPrices(p.extra_items),
      p.extra_items_payment_method || "-",
      (p.fine_amount || 0).toLocaleString(),
      (p.total_paid_mmk || 0).toLocaleString(),
      p.total_paid_gbp > 0 ? `${p.total_paid_gbp.toLocaleString()} GBP` : "-"
    ]);
    
    autoTable(doc, {
      startY: 20,
      head: [detailHeaders],
      body: detailRows,
      theme: "striped",
      headStyles: { fillColor: [63, 81, 181] },
      styles: { fontSize: 6.5, cellPadding: 1.5, font: hasMyanmarFont ? "Pyidaungsu" : "helvetica" },
      columnStyles: {
        4: { halign: "right" },
        5: { halign: "right" },
        7: { halign: "right" },
        9: { halign: "right" },
        10: { halign: "right" },
        11: { halign: "right" }
      }
    });
  }

  // Save the PDF
  doc.save(`Income_Report_${type}_${new Date().toISOString().slice(0, 10)}.pdf`);
};
