"""Add Dsicount

Revision ID: 03d1a81d17aa
Revises: 676ca4539935
Create Date: 2026-03-24 23:07:36.590038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d1a81d17aa'
down_revision: Union[str, Sequence[str], None] = '676ca4539935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('discount', sa.Float(), nullable=True))
    op.drop_column('courses', 'discount_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('discount_plan', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('courses', 'discount')
    # ### end Alembic commands ###
