"""Enhance

Revision ID: 0db1e5d5c133
Revises: 840d13e8baa0
Create Date: 2026-03-31 19:54:39.108467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db1e5d5c133'
down_revision: Union[str, Sequence[str], None] = '840d13e8baa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_course_batch_no', 'batches', ['course_id', 'batch_no'])
    op.add_column('courses', sa.Column('foc_items_cash_down', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('foc_items_installment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'foc_items_installment')
    op.drop_column('courses', 'foc_items_cash_down')
    op.drop_constraint('uq_course_batch_no', 'batches', type_='unique')
    # ### end Alembic commands ###
