"""Enhance

Revision ID: 0e4dcafa775f
Revises: 0db1e5d5c133
Create Date: 2026-03-31 19:57:37.906993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4dcafa775f'
down_revision: Union[str, Sequence[str], None] = '0db1e5d5c133'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'foc_items_cash_down')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('foc_items_cash_down', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
