"""move_batch_no_to_enrollment

Revision ID: 12d401062481
Revises: 73140dedb182
Create Date: 2026-03-18 12:02:55.840019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12d401062481'
down_revision: Union[str, Sequence[str], None] = '73140dedb182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'batch_no')
    op.add_column('enrollments', sa.Column('batch_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'batch_no')
    op.add_column('courses', sa.Column('batch_no', sa.String(), nullable=True))
    # ### end Alembic commands ###
