"""Fix

Revision ID: 1d989b0fa117
Revises: 8b1e0ee3d39f
Create Date: 2026-03-26 10:14:18.148564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d989b0fa117'
down_revision: Union[str, Sequence[str], None] = '8b1e0ee3d39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attendances_timetable_id'), 'attendances', ['timetable_id'], unique=False)
    op.drop_constraint('fk_student', 'timetables', type_='foreignkey')
    op.drop_column('timetables', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_student', 'timetables', 'users', ['student_id'], ['user_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_attendances_timetable_id'), table_name='attendances')
    # ### end Alembic commands ###
