"""add receipt_id to payment

Revision ID: 21cae259cb18
Revises: 66f225fa6cd2
Create Date: 2026-06-11 17:11:50.229592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21cae259cb18'
down_revision: Union[str, Sequence[str], None] = '66f225fa6cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teacher_notes_course_id', table_name='teacher_notes')
    op.drop_index('ix_teacher_notes_note_id', table_name='teacher_notes')
    op.drop_index('ix_teacher_notes_student_id', table_name='teacher_notes')
    op.drop_index('ix_teacher_notes_teacher_id', table_name='teacher_notes')
    op.drop_table('teacher_notes')
    op.drop_index('ix_grades_subject_id', table_name='grades')
    op.drop_index('ix_grades_teacher_id', table_name='grades')
    op.drop_constraint('grades_subject_id_fkey', 'grades', type_='foreignkey')
    op.drop_constraint('grades_teacher_id_fkey', 'grades', type_='foreignkey')
    op.drop_constraint('grades_course_id_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'courses', ['course_id'], ['course_id'], ondelete='CASCADE')
    op.drop_column('grades', 'remark')
    op.drop_column('grades', 'teacher_id')
    op.drop_column('grades', 'updated_at')
    op.drop_column('grades', 'subject_id')
    op.drop_column('grades', 'course_name')
    op.drop_constraint('payments_receipt_id_key', 'payments', type_='unique')
    op.create_index(op.f('ix_payments_receipt_id'), 'payments', ['receipt_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_receipt_id'), table_name='payments')
    op.create_unique_constraint('payments_receipt_id_key', 'payments', ['receipt_id'], postgresql_nulls_not_distinct=False)
    op.add_column('grades', sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('grades', sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_course_id_fkey', 'grades', 'courses', ['course_id'], ['course_id'], ondelete='SET NULL')
    op.create_foreign_key('grades_teacher_id_fkey', 'grades', 'users', ['teacher_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key('grades_subject_id_fkey', 'grades', 'subjects', ['subject_id'], ['subject_id'], ondelete='SET NULL')
    op.create_index('ix_grades_teacher_id', 'grades', ['teacher_id'], unique=False)
    op.create_index('ix_grades_subject_id', 'grades', ['subject_id'], unique=False)
    op.create_table('teacher_notes',
    sa.Column('note_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('note_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name='teacher_notes_course_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name='teacher_notes_student_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], name='teacher_notes_teacher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', name='teacher_notes_pkey')
    )
    op.create_index('ix_teacher_notes_teacher_id', 'teacher_notes', ['teacher_id'], unique=False)
    op.create_index('ix_teacher_notes_student_id', 'teacher_notes', ['student_id'], unique=False)
    op.create_index('ix_teacher_notes_note_id', 'teacher_notes', ['note_id'], unique=False)
    op.create_index('ix_teacher_notes_course_id', 'teacher_notes', ['course_id'], unique=False)
    # ### end Alembic commands ###
