"""update attendance model for course and subject

Revision ID: 32d61d4c3891
Revises: d9997a40797b
Create Date: 2026-03-26 12:35:18.217686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d61d4c3891'
down_revision: Union[str, Sequence[str], None] = 'd9997a40797b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.drop_constraint('uq_user_attendance_date_slot', 'attendances', type_='unique')
    op.create_index(op.f('ix_attendances_course_id'), 'attendances', ['course_id'], unique=False)
    op.create_index(op.f('ix_attendances_subject_id'), 'attendances', ['subject_id'], unique=False)
    op.create_unique_constraint('uq_user_attendance_date_slot_subject', 'attendances', ['user_id', 'attendance_date', 'slot', 'subject_id'])
    op.create_foreign_key(None, 'attendances', 'subjects', ['subject_id'], ['subject_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'attendances', 'courses', ['course_id'], ['course_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_constraint('uq_user_attendance_date_slot_subject', 'attendances', type_='unique')
    op.drop_index(op.f('ix_attendances_subject_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_course_id'), table_name='attendances')
    op.create_unique_constraint('uq_user_attendance_date_slot', 'attendances', ['user_id', 'attendance_date', 'slot'], postgresql_nulls_not_distinct=False)
    op.drop_column('attendances', 'subject_id')
    op.drop_column('attendances', 'course_id')
    # ### end Alembic commands ###
