"""add_student_contact_details

Revision ID: 3bd4e3fe0e30
Revises: 12d401062481
Create Date: 2026-03-18 12:12:37.645442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bd4e3fe0e30'
down_revision: Union[str, Sequence[str], None] = '12d401062481'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('parent_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('parent_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'parent_phone')
    op.drop_column('users', 'parent_name')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
