"""Fix

Revision ID: 3ee68879cdc6
Revises: initial_001
Create Date: 2026-03-21 21:42:07.997054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee68879cdc6'
down_revision: Union[str, Sequence[str], None] = 'initial_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('academic_year_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_name', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('academic_year_id')
    )
    op.create_index(op.f('ix_academic_years_academic_year_id'), 'academic_years', ['academic_year_id'], unique=False)
    op.create_index(op.f('ix_academic_years_year_name'), 'academic_years', ['year_name'], unique=True)
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_rooms_room_id'), 'rooms', ['room_id'], unique=False)
    op.create_index(op.f('ix_rooms_room_name'), 'rooms', ['room_name'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_code', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nrc', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('parent_phone', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('data_of_birth', sa.DateTime(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('activity_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('attendances',
    sa.Column('attendance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('check_today', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('user_id', 'attendance_date', 'slot', name='uq_user_attendance_date_slot')
    )
    op.create_index(op.f('ix_attendances_attendance_id'), 'attendances', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendances_user_id'), 'attendances', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('academicyear_id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('fee_full_payment', sa.Float(), nullable=True),
    sa.Column('fee_installment', sa.Float(), nullable=True),
    sa.Column('exam_fee', sa.Float(), nullable=True),
    sa.Column('exam_fee_gbp', sa.Float(), nullable=True),
    sa.Column('foc_items', sa.String(), nullable=True),
    sa.Column('discount_plan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academicyear_id'], ['academic_years.academic_year_id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_courses_academicyear_id'), 'courses', ['academicyear_id'], unique=False)
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=False)
    op.create_index(op.f('ix_courses_instructor_id'), 'courses', ['instructor_id'], unique=False)
    op.create_table('parent_student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('relationship_label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_index(op.f('ix_parent_student_parent_id'), 'parent_student', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_student_student_id'), 'parent_student', ['student_id'], unique=False)
    op.create_table('staff_attendances',
    sa.Column('attendance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.String(), nullable=True),
    sa.Column('check_out_time', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('user_id', 'attendance_date', name='uq_staff_attendance_date')
    )
    op.create_index(op.f('ix_staff_attendances_user_id'), 'staff_attendances', ['user_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_code', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('batch_no', sa.String(), nullable=True),
    sa.Column('payment_plan', sa.String(), nullable=True),
    sa.Column('downpayment', sa.Float(), nullable=True),
    sa.Column('installment_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_enrollment_code'), 'enrollments', ['enrollment_code'], unique=True)
    op.create_index(op.f('ix_enrollments_enrollment_id'), 'enrollments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('grade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('grade_point', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grade_id')
    )
    op.create_index(op.f('ix_grades_course_id'), 'grades', ['course_id'], unique=False)
    op.create_index(op.f('ix_grades_grade_id'), 'grades', ['grade_id'], unique=False)
    op.create_index(op.f('ix_grades_user_id'), 'grades', ['user_id'], unique=False)
    op.create_table('timetables',
    sa.Column('timetable_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('room_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    op.create_index(op.f('ix_timetables_course_id'), 'timetables', ['course_id'], unique=False)
    op.create_index(op.f('ix_timetables_timetable_id'), 'timetables', ['timetable_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('fine_amount', sa.Float(), nullable=True),
    sa.Column('fine_reason', sa.String(), nullable=True),
    sa.Column('extra_items_fee', sa.Float(), nullable=True),
    sa.Column('extra_items', sa.String(), nullable=True),
    sa.Column('exam_fee_paid_gbp', sa.Float(), nullable=True),
    sa.Column('exam_fee_paid_mmk', sa.Float(), nullable=True),
    sa.Column('exam_fee_currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.enrollment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_enrollment_id'), 'payments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_enrollment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_timetables_timetable_id'), table_name='timetables')
    op.drop_index(op.f('ix_timetables_course_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_grades_user_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_grade_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_course_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_enrollment_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_enrollment_code'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_staff_attendances_user_id'), table_name='staff_attendances')
    op.drop_table('staff_attendances')
    op.drop_index(op.f('ix_parent_student_student_id'), table_name='parent_student')
    op.drop_index(op.f('ix_parent_student_parent_id'), table_name='parent_student')
    op.drop_table('parent_student')
    op.drop_index(op.f('ix_courses_instructor_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_index(op.f('ix_courses_academicyear_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_attendances_user_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_attendance_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_user_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rooms_room_name'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_room_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_academic_years_year_name'), table_name='academic_years')
    op.drop_index(op.f('ix_academic_years_academic_year_id'), table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
