"""Add start_date and room to Course

Revision ID: 4ca886e59717
Revises: 94a8d35fcb9c
Create Date: 2026-03-17 17:15:19.899103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ca886e59717'
down_revision: Union[str, Sequence[str], None] = '94a8d35fcb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOTE:
    # This revision was auto-generated incorrectly (it attempted to drop most tables).
    # Keep it as a no-op to avoid destructive migrations on existing databases.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enrollment_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enrollment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('enrollments_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name=op.f('enrollments_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id', name=op.f('enrollments_pkey'))
    )
    op.create_index(op.f('ix_enrollments_enrollment_id'), 'enrollments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_enrollments_enrollment_code'), 'enrollments', ['enrollment_code'], unique=True)
    op.create_table('parent_student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relationship_label', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.user_id'], name=op.f('parent_student_parent_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name=op.f('parent_student_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('parent_student_pkey')),
    sa.UniqueConstraint('parent_id', 'student_id', name=op.f('uq_parent_student'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('grades',
    sa.Column('grade_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('grade_point', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('grades_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('grades_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grade_id', name=op.f('grades_pkey'))
    )
    op.create_index(op.f('ix_grades_grade_id'), 'grades', ['grade_id'], unique=False)
    op.create_table('staff_attendances',
    sa.Column('attendance_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attendance_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('check_out_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('staff_attendances_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id', name=op.f('staff_attendances_pkey')),
    sa.UniqueConstraint('user_id', 'attendance_date', name=op.f('uq_staff_attendance_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('courses',
    sa.Column('course_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('course_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('academicyear_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instructor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['academicyear_id'], ['academic_years.academic_year_id'], name=op.f('courses_academicyear_id_fkey')),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], name=op.f('courses_instructor_id_fkey')),
    sa.PrimaryKeyConstraint('course_id', name=op.f('courses_pkey'))
    )
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=False)
    op.create_index(op.f('ix_courses_course_id'), 'courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_table('attendances',
    sa.Column('attendance_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_today', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('attendances_user_id_fkey')),
    sa.PrimaryKeyConstraint('attendance_id', name=op.f('attendances_pkey'))
    )
    op.create_index(op.f('ix_attendances_attendance_id'), 'attendances', ['attendance_id'], unique=False)
    op.create_table('academic_years',
    sa.Column('academic_year_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('academic_year_id', name=op.f('academic_years_pkey'))
    )
    op.create_index(op.f('ix_academic_years_year_name'), 'academic_years', ['year_name'], unique=True)
    op.create_index(op.f('ix_academic_years_academic_year_id'), 'academic_years', ['academic_year_id'], unique=False)
    op.create_table('timetables',
    sa.Column('timetable_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], name=op.f('timetables_course_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timetable_id', name=op.f('timetables_pkey'))
    )
    op.create_index(op.f('ix_timetables_timetable_id'), 'timetables', ['timetable_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('data_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_user_code'), 'users', ['user_code'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
