"""add payment method

Revision ID: 546bf907825e
Revises: a64b1c0fea1e
Create Date: 2026-03-18 23:08:34.936999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546bf907825e'
down_revision: Union[str, Sequence[str], None] = 'a64b1c0fea1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_method')
    # ### end Alembic commands ###
