"""add subject_id to timetable

Revision ID: 591256209eed
Revises: 32d61d4c3891
Create Date: 2026-03-26 12:38:50.786335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591256209eed'
down_revision: Union[str, Sequence[str], None] = '32d61d4c3891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('subject_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_timetables_subject_id'), 'timetables', ['subject_id'], unique=False)
    op.create_foreign_key(None, 'timetables', 'subjects', ['subject_id'], ['subject_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    op.drop_index(op.f('ix_timetables_subject_id'), table_name='timetables')
    op.drop_column('timetables', 'subject_id')
    # ### end Alembic commands ###
