"""add_extra_items_payment_method

Revision ID: 5c692d942d4d
Revises: 21cae259cb18
Create Date: 2026-06-24 17:42:06.683046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c692d942d4d'
down_revision: Union[str, Sequence[str], None] = '21cae259cb18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('extra_items_payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'extra_items_payment_method')
    # ### end Alembic commands ###
