"""Add batch_id to timetables

Revision ID: 676ca4539935
Revises: d0e3a9753ea0
Create Date: 2026-03-24 20:10:43.189735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676ca4539935'
down_revision: Union[str, Sequence[str], None] = 'd0e3a9753ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_timetables_batch_id'), 'timetables', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'timetables', 'batches', ['batch_id'], ['batch_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'timetables', type_='foreignkey')
    op.drop_index(op.f('ix_timetables_batch_id'), table_name='timetables')
    op.drop_column('timetables', 'batch_id')
    # ### end Alembic commands ###
