"""added_course_fee_foc_fields

Revision ID: 6a15e795e879
Revises: efdc2010b4d5
Create Date: 2026-03-21 16:36:19.242214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a15e795e879'
down_revision: Union[str, Sequence[str], None] = 'efdc2010b4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('fee_full_payment', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('fee_installment', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('exam_fee_full', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('exam_fee_installment', sa.Float(), nullable=True))
    op.add_column('courses', sa.Column('foc_items', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'foc_items')
    op.drop_column('courses', 'exam_fee_installment')
    op.drop_column('courses', 'exam_fee_full')
    op.drop_column('courses', 'fee_installment')
    op.drop_column('courses', 'fee_full_payment')
    # ### end Alembic commands ###
