"""Fix

Revision ID: 8b1e0ee3d39f
Revises: d5a9701c6bc8
Create Date: 2026-03-26 09:51:25.875893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1e0ee3d39f'
down_revision: Union[str, Sequence[str], None] = 'd5a9701c6bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_timetables_teacher_id'), 'timetables', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetables_teacher_id'), table_name='timetables')
    # ### end Alembic commands ###
