"""Add fine and extra items

Revision ID: 8d00b4da5534
Revises: 449fc97e56ee
Create Date: 2026-03-21 16:52:42.037201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d00b4da5534'
down_revision: Union[str, Sequence[str], None] = '449fc97e56ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('exam_fee', sa.Float(), nullable=True))
    op.drop_column('courses', 'exam_fee_full')
    op.drop_column('courses', 'exam_fee_installment')
    op.add_column('payments', sa.Column('fine_amount', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('extra_items_fee', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('extra_items', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'extra_items')
    op.drop_column('payments', 'extra_items_fee')
    op.drop_column('payments', 'fine_amount')
    op.add_column('courses', sa.Column('exam_fee_installment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('exam_fee_full', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('courses', 'exam_fee')
    # ### end Alembic commands ###
