"""add_payments_and_slot

Revision ID: a64b1c0fea1e
Revises: 3bd4e3fe0e30
Create Date: 2026-03-18 14:04:33.118837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64b1c0fea1e'
down_revision: Union[str, Sequence[str], None] = '3bd4e3fe0e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('slot', sa.String(), nullable=False, server_default='Morning'))
    op.alter_column('attendances', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attendances', 'attendance_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('attendances', 'check_today',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_unique_constraint('uq_user_attendance_date_slot', 'attendances', ['user_id', 'attendance_date', 'slot'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_attendance_date_slot', 'attendances', type_='unique')
    op.alter_column('attendances', 'check_today',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('attendances', 'attendance_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('attendances', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('attendances', 'slot')
    # ### end Alembic commands ###
