"""Fix

Revision ID: aff7db7c5898
Revises: 61cd311c6851
Create Date: 2026-03-23 00:44:36.197026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff7db7c5898'
down_revision: Union[str, Sequence[str], None] = '61cd311c6851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('intended_course_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'intended_course_code')
    # ### end Alembic commands ###
