"""add_exam_fee_gbp_and_exam_fee_paid

Revision ID: b9e2e07afc9b
Revises: 8d00b4da5534
Create Date: 2026-03-21 17:10:54.991351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e2e07afc9b'
down_revision: Union[str, Sequence[str], None] = '8d00b4da5534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('exam_fee_gbp', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('exam_fee_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('exam_fee_currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'exam_fee_currency')
    op.drop_column('payments', 'exam_fee_paid')
    op.drop_column('courses', 'exam_fee_gbp')
    # ### end Alembic commands ###
