"""Model Add

Revision ID: bab6ed85c733
Revises: 591256209eed
Create Date: 2026-03-27 18:46:25.502370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab6ed85c733'
down_revision: Union[str, Sequence[str], None] = '591256209eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount_2', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('payment_method_2', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_method_2')
    op.drop_column('payments', 'amount_2')
    # ### end Alembic commands ###
