"""Fix

Revision ID: bfc8ab379f77
Revises: aff7db7c5898
Create Date: 2026-03-24 19:16:47.447489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc8ab379f77'
down_revision: Union[str, Sequence[str], None] = 'aff7db7c5898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_logs_timestamp'), 'activity_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_attendances_attendance_date'), 'attendances', ['attendance_date'], unique=False)
    op.add_column('courses', sa.Column('category', sa.String(), nullable=True))
    op.create_index(op.f('ix_enrollments_enrollment_date'), 'enrollments', ['enrollment_date'], unique=False)
    op.create_index(op.f('ix_rooms_created_at'), 'rooms', ['created_at'], unique=False)
    op.create_index(op.f('ix_rooms_updated_at'), 'rooms', ['updated_at'], unique=False)
    op.create_index(op.f('ix_staff_attendances_attendance_date'), 'staff_attendances', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_staff_attendances_attendance_date'), table_name='staff_attendances')
    op.drop_index(op.f('ix_rooms_updated_at'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_created_at'), table_name='rooms')
    op.drop_index(op.f('ix_enrollments_enrollment_date'), table_name='enrollments')
    op.drop_column('courses', 'category')
    op.drop_index(op.f('ix_attendances_attendance_date'), table_name='attendances')
    op.drop_index(op.f('ix_activity_logs_timestamp'), table_name='activity_logs')
    # ### end Alembic commands ###
