"""Add end_date to Course and change start_date type

Revision ID: c1855f10e281
Revises: 546bf907825e
Create Date: 2026-03-19 10:45:09.160966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1855f10e281'
down_revision: Union[str, Sequence[str], None] = '546bf907825e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('end_date', sa.Date(), nullable=True))
    op.alter_column('courses', 'start_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using="to_date(start_date, 'DD-MM-YYYY')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'start_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('courses', 'end_date')
    # ### end Alembic commands ###
