"""Enhance

Revision ID: d49a79f5b179
Revises: 0e4dcafa775f
Create Date: 2026-04-01 14:59:34.534801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd49a79f5b179'
down_revision: Union[str, Sequence[str], None] = '0e4dcafa775f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_enrollment_batches_batch_id', table_name='enrollment_batches')
    op.drop_index('ix_enrollment_batches_enrollment_id', table_name='enrollment_batches')
    op.drop_table('enrollment_batches')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_batches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('enrollment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], name='enrollment_batches_batch_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.enrollment_id'], name='enrollment_batches_enrollment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='enrollment_batches_subject_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='enrollment_batches_pkey')
    )
    op.create_index('ix_enrollment_batches_enrollment_id', 'enrollment_batches', ['enrollment_id'], unique=False)
    op.create_index('ix_enrollment_batches_batch_id', 'enrollment_batches', ['batch_id'], unique=False)
    # ### end Alembic commands ###
