"""Fix

Revision ID: e6ffe9655e33
Revises: 9bd9cb362a2b
Create Date: 2026-03-22 19:37:53.594902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ffe9655e33'
down_revision: Union[str, Sequence[str], None] = '9bd9cb362a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('how_did_you_hear', sa.String(), nullable=True))
    op.add_column('users', sa.Column('student_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'student_type')
    op.drop_column('users', 'how_did_you_hear')
    # ### end Alembic commands ###
