"""add_indexes

Revision ID: efdc2010b4d5
Revises: 1c58ee1535bc
Create Date: 2026-03-21 15:27:33.280178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdc2010b4d5'
down_revision: Union[str, Sequence[str], None] = '1c58ee1535bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_attendances_user_id'), 'attendances', ['user_id'], unique=False)
    op.create_index(op.f('ix_courses_academicyear_id'), 'courses', ['academicyear_id'], unique=False)
    op.create_index(op.f('ix_courses_instructor_id'), 'courses', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_grades_course_id'), 'grades', ['course_id'], unique=False)
    op.create_index(op.f('ix_grades_user_id'), 'grades', ['user_id'], unique=False)
    op.create_index(op.f('ix_parent_student_parent_id'), 'parent_student', ['parent_id'], unique=False)
    op.create_index(op.f('ix_parent_student_student_id'), 'parent_student', ['student_id'], unique=False)
    op.create_index(op.f('ix_payments_enrollment_id'), 'payments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_staff_attendances_user_id'), 'staff_attendances', ['user_id'], unique=False)
    op.create_index(op.f('ix_timetables_course_id'), 'timetables', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetables_course_id'), table_name='timetables')
    op.drop_index(op.f('ix_staff_attendances_user_id'), table_name='staff_attendances')
    op.drop_index(op.f('ix_payments_enrollment_id'), table_name='payments')
    op.drop_index(op.f('ix_parent_student_student_id'), table_name='parent_student')
    op.drop_index(op.f('ix_parent_student_parent_id'), table_name='parent_student')
    op.drop_index(op.f('ix_grades_user_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_course_id'), table_name='grades')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index(op.f('ix_courses_instructor_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_academicyear_id'), table_name='courses')
    op.drop_index(op.f('ix_attendances_user_id'), table_name='attendances')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    # ### end Alembic commands ###
