"""Fix

Revision ID: ffed2529e8c5
Revises: d84ec3187ee2
Create Date: 2026-03-24 19:55:50.185223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffed2529e8c5'
down_revision: Union[str, Sequence[str], None] = 'd84ec3187ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_staff_attendance_day')
    )
    op.create_index(op.f('ix_staff_attendance_date'), 'staff_attendance', ['date'], unique=False)
    op.create_index(op.f('ix_staff_attendance_user_id'), 'staff_attendance', ['user_id'], unique=False)
    op.create_table('batches',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_no', sa.String(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_batches_batch_id'), 'batches', ['batch_id'], unique=False)
    op.drop_index('ix_staff_attendances_attendance_date', table_name='staff_attendances')
    op.drop_index('ix_staff_attendances_user_id', table_name='staff_attendances')
    op.drop_table('staff_attendances')
    op.add_column('academic_years', sa.Column('academic_year_name', sa.String(), nullable=True))
    op.execute("UPDATE academic_years SET academic_year_name = year_name")
    op.alter_column('academic_years', 'academic_year_name', nullable=False)
    op.add_column('academic_years', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('academic_years', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('academic_years', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('academic_years', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_index('ix_academic_years_year_name', table_name='academic_years')
    op.create_index(op.f('ix_academic_years_academic_year_name'), 'academic_years', ['academic_year_name'], unique=True)
    op.drop_column('academic_years', 'year_name')
    op.add_column('attendances', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attendances_batch_id'), 'attendances', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'attendances', 'batches', ['batch_id'], ['batch_id'], ondelete='SET NULL')
    op.alter_column('courses', 'course_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('courses', 'academicyear_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_courses_course_name', table_name='courses')
    op.add_column('enrollments', sa.Column('batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_enrollments_batch_id'), 'enrollments', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'enrollments', 'batches', ['batch_id'], ['batch_id'], ondelete='SET NULL')
    op.add_column('grades', sa.Column('student_id', sa.Integer(), nullable=True))
    op.drop_index('ix_grades_user_id', table_name='grades')
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.drop_constraint('grades_user_id_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'users', ['student_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('grades', 'user_id')
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('payments', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('payments', 'month',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.drop_index('ix_rooms_updated_at', table_name='rooms')
    op.alter_column('users', 'user_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'data_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_updated_at', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_updated_at', 'users', ['updated_at'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.alter_column('users', 'data_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'user_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_rooms_updated_at', 'rooms', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.alter_column('payments', 'month',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('payments', 'enrollment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'created_at')
    op.add_column('grades', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_user_id_fkey', 'grades', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.create_index('ix_grades_user_id', 'grades', ['user_id'], unique=False)
    op.drop_column('grades', 'student_id')
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.drop_index(op.f('ix_enrollments_batch_id'), table_name='enrollments')
    op.drop_column('enrollments', 'batch_id')
    op.create_index('ix_courses_course_name', 'courses', ['course_name'], unique=False)
    op.alter_column('courses', 'academicyear_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'course_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_index(op.f('ix_attendances_batch_id'), table_name='attendances')
    op.drop_column('attendances', 'batch_id')
    op.add_column('academic_years', sa.Column('year_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_academic_years_academic_year_name'), table_name='academic_years')
    op.create_index('ix_academic_years_year_name', 'academic_years', ['year_name'], unique=True)
    op.alter_column('academic_years', 'end_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('academic_years', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('academic_years', 'updated_at')
    op.drop_column('academic_years', 'created_at')
    op.drop_column('academic_years', 'academic_year_name')
    op.create_table('staff_attendances',
    sa.Column('attendance_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attendance_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_in_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('check_out_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='staff_attendances_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id', name='staff_attendances_pkey'),
    sa.UniqueConstraint('user_id', 'attendance_date', name='uq_staff_attendance_date', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_staff_attendances_user_id', 'staff_attendances', ['user_id'], unique=False)
    op.create_index('ix_staff_attendances_attendance_date', 'staff_attendances', ['attendance_date'], unique=False)
    op.drop_index(op.f('ix_batches_batch_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_staff_attendance_user_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_staff_attendance_date'), table_name='staff_attendance')
    op.drop_table('staff_attendance')
    # ### end Alembic commands ###
